use_frameworks!

target 'SJListKit_Example' do
  pod 'SJListKit', :path => '../'

  target 'SJListKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3'
    pod 'Nimble', '~> 7.3'
  end
end
